name: Unzip mirror to GitHub Pages

on:
  workflow_dispatch: {}   # run manually from the Actions tab

permissions:
  contents: write         # allow the workflow to commit code

jobs:
  unzip_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Confirm ZIP exists
        run: |
          test -f ttoka-mirror.zip || { echo "ttoka-mirror.zip not found in repo root"; exit 1; }
          ls -lh ttoka-mirror.zip

      # choose ONE target: root or /docs (docs is nice if you want a tidy repo)
      - name: Prepare target folder (/docs)
        run: |
          mkdir -p docs
          rm -rf docs/*

      - name: Unzip into /docs
        run: |
          # Unzip everything into /docs
          unzip -o ttoka-mirror.zip -d docs
          # If the zip contains a host subfolder (e.g., ttoka.org), flatten it:
          # Move first-level folder contents up if there are only folders at top-level
          if [ "$(ls -1 docs | wc -l)" -eq 1 ] && [ -d "docs/$(ls -1 docs)" ]; then
            TOP="docs/$(ls -1 docs)"
            shopt -s dotglob
            mv "$TOP"/* docs/ || true
            rmdir "$TOP" || true
          fi
          # Ensure an index.html exists at the target
          (ls docs/index.html >/dev/null 2>&1) || echo "WARNING: No docs/index.html found."

      - name: Commit and push
        run: |
          git config user.name  "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add -A
          git commit -m "Publish mirror to /docs" || echo "Nothing to commit"
          git push

